name: "Servian TechChallenge"
on:
  push:
    # paths:
    # - 'terraform/**'
    branches:
      - main
  pull_request:
    # paths:
    # - 'terraform/**'
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_BACKEND_BUCKET: andreazza
  TF_BACKEND_KEY: srvntechchallenge
  REFRESH_DB: true
  DESTROY_EVERYTHING: false


jobs:
  infra_plan:
    name: "Plan Infra"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Plan Infra
        run: make plan_infra

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: infra plan
          path: terraform/infra.plan

  infra_apply:
    name: "Apply infra"
    runs-on: ubuntu-latest
    needs: infra_plan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: infra plan
          path: terraform
      
      - name: Terraform Apply Infra
        run: make apply_infra


  # prep_db:
  #   if: ${{ env.REFRESH_DB == 'true' }} # || github.ref == 'refs/heads/main'
  #   name: Terraform Prep DB
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Terraform Prep DB
  #       id: prep_db
  #       run: make apply


  destroy_everything:
    name: "Destroy everything"
    runs-on: ubuntu-latest
    needs: infra_apply
    if: ${{ DESTROY_EVERYTHING == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Terraform Apply Infra
        run: make destroy_everything
