name: "Servian TechChallenge"
on:
  push:
    # paths:
    # - 'terraform/**'
    branches:
      - main
  pull_request:
    # paths:
    # - 'terraform/**'
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_BACKEND_BUCKET: andreazza
  TF_BACKEND_KEY: srvntechchallenge
  REFRESH_DB: true


jobs:
  infra_plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Plan
        id: plan
        run: make plan_infra

  infra_apply:
    name: "Apply infra"
    runs-on: ubuntu-latest
    needs: infra_plan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Apply Infra
        id: plan
        run: make apply_infra


#   prep_db:
#     name: Terraform Prep DB
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Terraform Prep DB
#         id: prep_db
#         if: ${{ env.REFRESH_DB == 'true' }} || github.ref == 'refs/heads/main'
#         run: make apply
