name: "Servian TechChallenge"
on:
  push:
    # paths:
    # - 'terraform/**'
    branches:
      - main
  pull_request:
    # paths:
    # - 'terraform/**'
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_BACKEND_BUCKET: andreazza
  TF_BACKEND_KEY: srvntechchallenge
  REFRESH_DB: false
  DESTROY: false


jobs:
  # infra_plan:
  #   name: "Plan Infra"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Terraform Plan Infra
  #       run: make plan_infra

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: infra plan
  #         path: terraform/infra.plan
  #         retention-days: 5

  # infra_apply:
  #   name: "Apply infra"
  #   runs-on: ubuntu-latest
  #   needs: infra_plan
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Download a single artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: infra plan
  #         path: terraform
      
  #     - name: Terraform Apply Infra
  #       run: make apply_infra


  prep_db:
    name: Terraform Prep DB
    runs-on: ubuntu-latest
    # env:
    #   workflow_token: ${{ secrets.WORKFLOW_TOKEN }}
    steps:
      - name: Checkout
        if: ${{ env.REFRESH_DB == 'true' }} # || github.ref == 'refs/heads/main'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Terraform Prep DB
        if: ${{ env.REFRESH_DB == 'true' }} 
        # run: make apply
        run: echo "good stuff"

      - name: Update var
        if: ${{ env.REFRESH_DB == 'true' }} 
        run: |
          sed -i "s/REFRESH_DB: false/REFRESH_DB: false/" .github/workflows/main.yml
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git add .
          git commit -m "Variable change"
          git push





  destroy_everything:
    name: "Destroy everything"
    runs-on: ubuntu-latest
    # needs: infra_apply
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ env.DESTROY == 'true' }}
      
      - name: Terraform Apply Infra
        if: ${{ env.DESTROY == 'true' }}
        # run: make destroy_everything
        run: echo "nice mate"
